- name: print msg 
  hosts: all
  tasks:
    - name: Gather Facts #gather facts
      debug:
        msg: "Hello World"
    - name: print os 
      debug:
        msg: "{{ansible_os_family}}"   #print facts
    
    
