---
- name: Install and start Nginx service
  hosts: your_target_host
  become: yes  # To escalate privilege, often required for package installation and service management
  tasks:
    - name: Install Nginx package
      yum:
        name: nginx
        state: present  # Ensure Nginx package is present

    - name: Start Nginx service and enable it on boot
      systemd:
        name: nginx
        state: started  # Ensure Nginx service is started
        enabled: yes   # Ensure Nginx service starts on boot
